### ISSUE TITLE
I see a bump

### ISSUE THREAD

**Issue by anonymuse** [ryansydnor/holochrome#1]
Awesome product, noticed that there's a mis-alignment in one of your logos:

https://github.com/ryansydnor/holochrome/blob/master/holochrome-920x680.png

That's the one you use on your product page, so thought I'd mention it.

**Comment by ryansydnor** [comment]
This was fixed in the move to Bridgewater's repo [here](https://github.com/Bridgewater/holochrome).

**Comment by anonymuse** [comment]
Thanks, and looks good over there in the new repo! 👍
