### ISSUE TITLE
Rotate session seamlessly without being logged out

### ISSUE THREAD

**Issue by walterking** [ryansydnor/holochrome#2]
To continue the discussion at https://github.com/AdRoll/hologram/issues/67

> https://github.com/gitlon/CASTER

> Agree! I tried to do that, but basically failed. I grab a new session token every 20 minutes. Unfortunately, the AWS console doesn't react well to the "injection" of new credentials. It seems like whenever the session cookie changes at all, it logs you out. I've had inconsistent behavior with this approach - sometimes it logs me out completely and redirects, sometimes it gives me a "you've been logged out" popup, and sometimes it just keeps chugging along happily. Would love any/all help solidifying this!

its probably been a year since I looked into it, but trouble injecting credentials sounds familiar, most likely some js variable in addition to the cookie. But i gave up on getting it working and instead have a tampermonkey plugin that re-logs in(since our saml saves the session longer, just a series of redirects) after aws redirects us to the signin page.

**Comment by ryansydnor** [comment]
@walterking - apologies for asking you to move the discussion again, but the repo has moved to Bridgewater's organization [here](https://github.com/Bridgewater/holochrome). Can we move there?

**Comment by walterking** [comment]
sure, whereever

**Comment by ryansydnor** [comment]
Thanks, hopefully the last time!

**Comment by ryansydnor** [comment]
Would also love if you updated the link in hologram's README @walterking !

**Comment by walterking** [comment]
already did!

**Comment by ryansydnor** [comment]
Such agility. Much speed. Wow!
